[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Ryan Wible <ryanwiblecoding@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
orjson = "^3.9.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"